import type { BillData } from "./types";

export interface DemoBill {
  id: string;
  title: string;
  subtitle: string;
  billTotal: number;
  savings: number;
  data: BillData;
}

export const DEMO_BILLS: DemoBill[] = [
  {
    id: "er-visit",
    title: "ER Visit",
    subtitle: "Overcharges on common services",
    billTotal: 8421,
    savings: 3247,
    data: {
      patient_name: "Demo Patient",
      date_of_service: "2024-01-15",
      provider_name: "Metro General Hospital Emergency Dept",
      provider_address: "123 Healthcare Ave, Pittsburgh, PA 15213",
      total_charges: 8421.0,
      total_savings: 3247,
      errors_found: 4,
      line_items: [
        {
          description: "Emergency room visit, Level 4",
          cpt_code: "99284",
          quantity: 1,
          unit_price: 1850,
          total: 1850,
          date: "2024-01-15",
          fair_price: 892,
          savings: 958,
          has_error: true,
        },
        {
          description: "Comprehensive metabolic panel",
          cpt_code: "80053",
          quantity: 1,
          unit_price: 425,
          total: 425,
          date: "2024-01-15",
          fair_price: 42,
          savings: 383,
          has_error: true,
        },
        {
          description: "Chest X-ray, 2 views",
          cpt_code: "71046",
          quantity: 1,
          unit_price: 680,
          total: 680,
          date: "2024-01-15",
          fair_price: 95,
          savings: 585,
          has_error: true,
        },
        {
          description: "IV infusion, therapeutic",
          cpt_code: "96365",
          quantity: 2,
          unit_price: 825,
          total: 1650,
          date: "2024-01-15",
          fair_price: 180,
          savings: 1290,
          has_error: true,
        },
        {
          description: "Urinalysis with microscopy",
          cpt_code: "81001",
          quantity: 1,
          unit_price: 156,
          total: 156,
          date: "2024-01-15",
          fair_price: null,
          savings: null,
          has_error: false,
        },
      ],
      insurance_info: {
        insurance_paid: 5200,
        patient_responsibility: 3221,
        deductible_applied: 2500,
        copay: 250,
      },
    },
  },
  {
    id: "outpatient-surgery",
    title: "Outpatient Surgery",
    subtitle: "Duplicate charges detected",
    billTotal: 15890,
    savings: 4120,
    data: {
      patient_name: "Demo Patient",
      date_of_service: "2024-02-03",
      provider_name: "SurgiCare Ambulatory Surgery Center",
      provider_address: "456 Medical Center Dr, Pittsburgh, PA 15232",
      total_charges: 15890.0,
      total_savings: 4120,
      errors_found: 3,
      line_items: [
        {
          description: "Knee arthroscopy with meniscus repair",
          cpt_code: "29881",
          quantity: 1,
          unit_price: 8750,
          total: 8750,
          date: "2024-02-03",
          fair_price: 5630,
          savings: 3120,
          has_error: true,
        },
        {
          description: "Anesthesia, knee surgery",
          cpt_code: "01382",
          quantity: 1,
          unit_price: 1850,
          total: 1850,
          date: "2024-02-03",
          fair_price: 1250,
          savings: 600,
          has_error: true,
        },
        {
          description: "Anesthesia, knee surgery (DUPLICATE)",
          cpt_code: "01382",
          quantity: 1,
          unit_price: 1850,
          total: 1850,
          date: "2024-02-03",
          fair_price: 0,
          savings: 400,
          has_error: true,
        },
        {
          description: "Recovery room",
          cpt_code: "99211",
          quantity: 1,
          unit_price: 420,
          total: 420,
          date: "2024-02-03",
          fair_price: null,
          savings: null,
          has_error: false,
        },
      ],
      insurance_info: {
        insurance_paid: 9200,
        patient_responsibility: 6690,
        deductible_applied: 2000,
        copay: 150,
      },
    },
  },
  {
    id: "routine-checkup",
    title: "Routine Checkup",
    subtitle: "Upcoding on office visit",
    billTotal: 847,
    savings: 320,
    data: {
      patient_name: "Demo Patient",
      date_of_service: "2024-03-10",
      provider_name: "Family Medicine Associates",
      provider_address: "789 Oak Street, Pittsburgh, PA 15217",
      total_charges: 847.0,
      total_savings: 320,
      errors_found: 2,
      line_items: [
        {
          description: "Office visit, established patient, Level 4",
          cpt_code: "99214",
          quantity: 1,
          unit_price: 285,
          total: 285,
          date: "2024-03-10",
          fair_price: 165,
          savings: 120,
          has_error: true,
        },
        {
          description: "Preventive visit, 40-64 years",
          cpt_code: "99386",
          quantity: 1,
          unit_price: 350,
          total: 350,
          date: "2024-03-10",
          fair_price: 210,
          savings: 140,
          has_error: true,
        },
        {
          description: "Lipid panel",
          cpt_code: "80061",
          quantity: 1,
          unit_price: 89,
          total: 89,
          date: "2024-03-10",
          fair_price: 29,
          savings: 60,
          has_error: true,
        },
        {
          description: "EKG, 12 leads",
          cpt_code: "93000",
          quantity: 1,
          unit_price: 123,
          total: 123,
          date: "2024-03-10",
          fair_price: null,
          savings: null,
          has_error: false,
        },
      ],
      insurance_info: {
        insurance_paid: 520,
        patient_responsibility: 327,
        deductible_applied: 0,
        copay: 30,
      },
    },
  },
];

export function getDemoBill(id: string): DemoBill | undefined {
  return DEMO_BILLS.find((b) => b.id === id);
}
